-- Add 20 curated international & Africa-focused grants (July–September 2026)
INSERT INTO public.opportunities (
  title,
  provider,
  category,
  description,
  link,
  deadline,
  event_date,
  state,
  is_verified,
  is_remote,
  level
)
VALUES
  -- August 2026 deadlines
  (
    'STDF Project and Project Preparation Grants',
    'Standards and Trade Development Facility (STDF)',
    'grant',
    'Funding for projects and project preparation that improve sanitary and phytosanitary (SPS) capacity and facilitate safe trade in developing countries.',
    'https://www.standardsfacility.org/project/apply',
    '2026-08-01T23:59:59Z',
    NULL,
    'International',
    true,
    true,
    NULL
  ),
  (
    'Internet Society Foundation Common Good Cyber Fund',
    'Internet Society Foundation',
    'grant',
    'Supports initiatives that strengthen cybersecurity, digital trust, and resilience for communities around the world.',
    'https://www.isocfoundation.org/grant-programme/common-good-cyber-fund/',
    '2026-08-04T23:59:59Z',
    NULL,
    'International',
    true,
    true,
    NULL
  ),
  (
    'Urgent Action Fund-Africa: Women''s Rights Organisations and Networks Grant',
    'Urgent Action Fund-Africa',
    'grant',
    'Grant supporting African women''s rights organizations and networks advancing gender justice and social change.',
    'https://www.uaf-africa.org/news_and_events/investing-in-womens-rights-organisations-and-networks-in-africa/',
    '2026-08-12T23:59:59Z',
    NULL,
    'International',
    true,
    true,
    NULL
  ),
  (
    'Spencer Foundation Vision Grants',
    'Spencer Foundation',
    'grant',
    'Supports collaborative planning projects that develop innovative ideas to improve education research.',
    'https://www.spencer.org/grant_types/vision-grants',
    '2026-08-12T23:59:59Z',
    NULL,
    'International',
    true,
    true,
    NULL
  ),
  (
    'New Africa Fund: Africa Fundraising Incubator',
    'New Africa Fund',
    'grant',
    'Supports African organizations through fundraising training, mentorship, and funding opportunities.',
    'https://www.newafricafund.org/afigrants',
    '2026-08-14T23:59:59Z',
    NULL,
    'Africa',
    true,
    true,
    NULL
  ),
  (
    'Blue Ambition Fund 2026',
    'Wilde Ganzen',
    'grant',
    'Funds initiatives promoting sustainable marine conservation, coastal livelihoods, and ocean restoration.',
    'https://www.wildeganzen.org/programs/blue-ambition-fund/baf-call-for-applications',
    '2026-08-15T23:59:59Z',
    NULL,
    'International',
    true,
    true,
    NULL
  ),
  (
    'Africa Health Collaborative Research Fund',
    'Africa Health Collaborative',
    'grant',
    'Research funding supporting collaborative health research projects across Africa.',
    'https://africahealthcollaborative.org/research/research-fund/',
    '2026-08-15T23:59:59Z',
    NULL,
    'Africa',
    true,
    true,
    NULL
  ),
  (
    'adidas Foundation: Moving for Change – East Africa',
    'adidas Foundation',
    'grant',
    'Supports organizations using sport to create positive social impact among young people in East Africa.',
    'https://www.adidasfoundation.org/rfp/moving-for-change-east-africa',
    '2026-08-21T23:59:59Z',
    NULL,
    'East Africa',
    true,
    true,
    NULL
  ),
  (
    'IDRC ANeSA Research Grants',
    'International Development Research Centre (IDRC)',
    'grant',
    'Research grants addressing neglected areas in sexual and reproductive health across Africa.',
    'https://idrc-crdi.ca/en/funding/call-letters-interest-addressing-neglected-areas-sexual-and-reproductive-health-and-0',
    '2026-08-23T23:59:59Z',
    NULL,
    'Africa',
    true,
    true,
    NULL
  ),
  (
    'FoodSafety4Africa Open Call 2',
    'FoodSafety4Africa',
    'grant',
    'Supports innovations and initiatives that strengthen food safety systems across Africa.',
    'https://foodsafety4africa.eu/open-call/',
    '2026-08-31T23:59:59Z',
    NULL,
    'Africa',
    true,
    true,
    NULL
  ),
  -- September 2026 deadlines
  (
    'GAFSP Ninth Call for Country-Led Projects',
    'Global Agriculture and Food Security Program (GAFSP)',
    'grant',
    'Funding for country-led agricultural projects that improve food security and strengthen resilient food systems.',
    'https://www.gafspfund.org/9th-call-proposals',
    '2026-09-15T23:59:59Z',
    NULL,
    'International',
    true,
    true,
    NULL
  ),
  (
    'British Council Researcher Challenges Grants',
    'British Council',
    'grant',
    'Supports international research collaborations tackling global development challenges.',
    'https://opportunities-insight.britishcouncil.org/short-articles/opportunities/researcher-challenges-grants-2026',
    '2026-09-17T23:59:59Z',
    NULL,
    'International',
    true,
    true,
    NULL
  ),
  (
    'IDRC–SGCI STISA 2034 Multilateral Research Call',
    'International Development Research Centre (IDRC)',
    'grant',
    'Research funding supporting science, technology, and innovation initiatives across Africa.',
    'https://idrc-crdi.ca/en/funding/supporting-stisa-2034-sgci-multilateral-research-call-advancing-africas-science-technology',
    '2026-09-25T23:59:59Z',
    NULL,
    'Africa',
    true,
    true,
    NULL
  ),
  (
    'Encephalitis International Africa Seed Funding',
    'Encephalitis International',
    'grant',
    'Seed funding for projects improving awareness, research, treatment, and support for encephalitis in Africa.',
    'https://www.encephalitis.info/grants-available/',
    '2026-09-30T23:59:59Z',
    NULL,
    'Africa',
    true,
    true,
    NULL
  ),
  (
    'British Council Springboard Research Grants',
    'British Council',
    'grant',
    'Supports international research partnerships between researchers in eligible countries and institutions in Europe.',
    'https://opportunities-insight.britishcouncil.org/short-articles/opportunities/springboard-2026-research-grants-france-germany-spain',
    '2026-09-30T23:59:59Z',
    NULL,
    'International',
    true,
    true,
    NULL
  ),
  -- Rolling / Open all year
  (
    'Rufford Small Grants for Nature Conservation',
    'Rufford Foundation',
    'grant',
    'Provides grants for nature conservation and biodiversity projects led by early-career conservationists worldwide. Rolling applications accepted throughout the year.',
    'https://apply.ruffordsmallgrants.org/',
    NULL,
    NULL,
    'International',
    true,
    true,
    NULL
  ),
  (
    'Front Line Defenders Protection Grants',
    'Front Line Defenders',
    'grant',
    'Emergency protection grants for human rights defenders facing security threats and risks. Rolling applications accepted throughout the year.',
    'https://www.frontlinedefenders.org/en/programme/protection-grants',
    NULL,
    NULL,
    'International',
    true,
    true,
    NULL
  ),
  (
    'Women''s Peace and Humanitarian Fund Rapid Response Window',
    'Women''s Peace and Humanitarian Fund (WPHF)',
    'grant',
    'Rapid-response funding for women human rights defenders, peacebuilders, and women-led organizations. Open all year.',
    'https://wphfund.org/rrw/',
    NULL,
    NULL,
    'International',
    true,
    true,
    NULL
  ),
  (
    'CIVICUS Crisis Response Fund',
    'CIVICUS',
    'grant',
    'Emergency funding for civil society organizations and activists responding to crises affecting civic space. Rolling applications accepted throughout the year.',
    'https://www.civicus.org/index.php/engage-and-act/explore-resourcing-opportunities/crisis-response-fund',
    NULL,
    NULL,
    'International',
    true,
    true,
    NULL
  ),
  (
    'The Pollination Project Seed Grants',
    'The Pollination Project',
    'grant',
    'Daily seed grants supporting early-stage social impact projects and community-led initiatives worldwide. Rolling applications accepted throughout the year.',
    'https://thepollinationproject.org/apply/',
    NULL,
    NULL,
    'International',
    true,
    true,
    NULL
  );
