// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vdliauwtxklhlkltqqua.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZkbGlhdXd0eGtsaGxrbHRxcXVhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjczNzI3NTgsImV4cCI6MjA4Mjk0ODc1OH0.OQVOHYxBwOx55jC5wC-8uLYanbs-4cf0IJCBsZ3picQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

// Force cleanup of old sessions from different projects
const cleanOldSessions = () => {
  try {
    const keys = Object.keys(localStorage);
    keys.forEach(key => {
      // If it's a supabase token but NOT for our current project
      if (key.startsWith('sb-') && !key.includes('vdliauwtxklhlkltqqua')) {
        console.log('Cleaning up old session:', key);
        localStorage.removeItem(key);
      }
    });
  } catch (e) {
    console.error('Error cleaning sessions:', e);
  }
};

cleanOldSessions();